spring:
  profiles:
    #active: dev
    #default: dev
    group:
      dev:
      test: common
      prod: common
default:
  string: default property
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: dev
    password:
server:
  port: 7777
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: test
    password: test1234!
server:
  port: 8888
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/prod
    username: prod
    password: prod1234!
server:
  port: 9999
---
spring:
  config:
    activate:
      on-profile: common
common:
  string: common property
