CREATE TABLE PUBLIC.TB_CODE (
    CODE_TYPE VARCHAR NOT NULL,
    CODE VARCHAR NOT NULL,
    VALUE VARCHAR NOT NULL,
    ACTIVE VARCHAR NULL,
    CREATED TIMESTAMPTZ NULL,
    UPDATED TIMESTAMPTZ NULL,
    CONSTRAINT "CODE_PK" PRIMARY KEY (CODE_TYPE, CODE)
);
CREATE INDEX CODE_INDEX_UPDATED ON PUBLIC.TB_CODE USING BTREE (UPDATED);

CREATE TABLE PUBLIC.TB_CUSTOMER (
    ID VARCHAR NOT NULL,
    "NAME" VARCHAR NOT NULL,
    BIRTHDAY VARCHAR NULL,
    GENDER VARCHAR NULL,
    ADDRESS VARCHAR NULL,
    PHONE_NUMBER VARCHAR NULL,
    "TYPE" VARCHAR NULL,
    CREATED TIMESTAMPTZ NOT NULL,
    UPDATED TIMESTAMPTZ NOT NULL,
    CONSTRAINT CUSTOMER_PK PRIMARY KEY (ID)
);
CREATE INDEX CUSTOMER_INDEX_NAME ON PUBLIC.TB_CUSTOMER USING BTREE (NAME);

CREATE TABLE PUBLIC.TB_DEPT (
    ID VARCHAR NOT NULL,
    "NAME" VARCHAR NULL,
    CREATED TIMESTAMPTZ NOT NULL,
    UPDATED TIMESTAMPTZ NOT NULL,
    CONSTRAINT "DEPT_PK" PRIMARY KEY (ID)
);
CREATE INDEX DEPT_INDEX_UPDATED ON PUBLIC.TB_DEPT USING BTREE (UPDATED);

CREATE TABLE PUBLIC.TB_SERVICE_REQUEST (
    ID VARCHAR NOT NULL,
    TITLE VARCHAR NULL,
    CUSTOMER_ID VARCHAR NOT NULL,
    "TYPE" VARCHAR NULL,
    DETAIL VARCHAR NULL,
    STATUS VARCHAR NOT NULL,
    CALL_AGENT_ID VARCHAR NULL,
    VOC_ASSGNEE_ID VARCHAR NULL,
    VOC_ASSGNEE_DEPT_ID VARCHAR NULL,
    CREATED TIMESTAMPTZ NOT NULL,
    UPDATED TIMESTAMPTZ NOT NULL,
    CONSTRAINT SERVICE_REQUEST_PK PRIMARY KEY (ID)
);
CREATE INDEX SERVICE_REQUEST_INDEX_BYCUSTOMER ON PUBLIC.TB_SERVICE_REQUEST USING BTREE (CUSTOMER_ID);
CREATE INDEX SERVICE_REQUEST_INDEX_UPDATED ON PUBLIC.TB_SERVICE_REQUEST USING BTREE (UPDATED);

CREATE TABLE PUBLIC.TB_USER (
    ID VARCHAR NOT NULL,
    "NAME" VARCHAR NULL,
    PHONE_NUMBER VARCHAR NULL,
    EMAIL VARCHAR NULL,
    CREATED TIMESTAMPTZ NOT NULL,
    UPDATED TIMESTAMPTZ NOT NULL,
    CONSTRAINT USER_PK PRIMARY KEY (ID)
);