services:
  mysql:
    image: 'mysql:latest'
    ports:
      - '13306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      TZ: Asia/Seoul
    volumes:
      - ./src/main/resources/initdb:/docker-entrypoint-initdb.d
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
