spring:
  application:
    name: spring-boot-batch
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  datasource:
    meta-db:
      pool-name: meta-db
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:13306/meta-db
      username: test
      password: test1!
    data-db:
      pool-name: data-db
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:13306/data-db
      username: test
      password: test1!
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:test
#    username: sa
#    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  docker:
    compose:
      skip:
        in-tests: false # 테스트를 실행할 때 Docker Compose 지원 스킵 여부 (true[기본값], false)
