spring:
  application:
    name: spring-boot-cache
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace
    org.springframework.cache.interceptor: trace
management:
  endpoints:
    web:
      exposure:
        include: "metrics,caches"
