spring:
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false
    defer-datasource-initialization: true
  data:
    redis:
      host: localhost
      port: 6379
  docker:
    compose:
      enabled: true
      lifecycle-management: start_and_stop
      skip:
        in-tests: false
      stop:
        command: down
        timeout: 1m
